# Generated by Django 3.1.4 on 2020-12-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Título')),
                ('price', models.DecimalField(decimal_places=2, help_text='Favor, incluir até 6 dígitos, com 2 casas decimais', max_digits=6, verbose_name='Preço')),
                ('image', models.ImageField(max_length=200, upload_to='product')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('reviewScore', models.DecimalField(decimal_places=1, help_text='Favor, incluir até 3 dígitos, com 1 casa decimal', max_digits=3, null=True, verbose_name='Pontuação do produto')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('favorite', models.ManyToManyField(to='api.Product', verbose_name='Produtos favoritos')),
            ],
        ),
    ]
